version: '3.8'

# Development overrides for docker-compose.yml
services:
  n8n:
    environment:
      - NODE_ENV=development
      - N8N_LOG_LEVEL=debug
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_SECURE_COOKIE=false
    ports:
      - "5678:5678"  # Expose on all interfaces for development
    volumes:
      - ./workflows:/home/node/.n8n/workflows:rw  # Mount workflows for easy editing
      - ./nodes:/home/node/.n8n/nodes:rw  # Mount custom nodes
    command: start --tunnel  # Enable tunnel for webhooks during development

  # Remove worker in development to simplify debugging
  n8n-worker:
    deploy:
      replicas: 0

  # Add a lightweight database admin tool for development
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - n8n-network
    depends_on:
      - postgres

volumes:
  pgadmin_data:
    driver: local
